FROM mcr.microsoft.com/devcontainers/base:bullseye

RUN apt update && apt install -y libglib2.0-0 libnspr4 libnss3 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libcairo2 libgtk-3-0 libgbm1 libasound2